name: Daily Price Scrape

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: MONGODB_URI

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install System Dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libnss3 libatk-bridge2.0-0 libgtk-3-0 libxss1 libasound2t64

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DATABASE_NAME: keells-price-tracker
        run: node scraper.js
